{% set version = "1.7.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-statsexpressions
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/statsExpressions_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/statsExpressions/statsExpressions_{{ version }}.tar.gz
  sha256: 20d8e54bc4ca8cffefe828107d709ebb4131c4a6177cbd736612d1787e5ac92d

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-afex >=1.4_1
    - r-bayesfactor >=0.9.12_4.7
    - r-bayestestr >=0.15.0
    - r-correlation >=0.8.6
    - r-datawizard >=0.13.0
    - r-dplyr >=1.1.4
    - r-effectsize >=0.8.9
    - r-glue >=1.8.0
    - r-insight >=1.0.0
    - r-magrittr >=2.0.3
    - r-parameters >=0.24.0
    - r-performance >=0.12.4
    - r-pmcmrplus >=1.9.12
    - r-purrr >=1.0.2
    - r-rlang >=1.1.4
    - r-rstantools >=2.4.0
    - r-tidyr >=1.3.1
    - r-withr >=3.0.2
    - r-wrs2 >=1.1_6
    - r-zeallot >=0.1.0
  run:
    - r-base
    - r-afex >=1.4_1
    - r-bayesfactor >=0.9.12_4.7
    - r-bayestestr >=0.15.0
    - r-correlation >=0.8.6
    - r-datawizard >=0.13.0
    - r-dplyr >=1.1.4
    - r-effectsize >=0.8.9
    - r-glue >=1.8.0
    - r-insight >=1.0.0
    - r-magrittr >=2.0.3
    - r-parameters >=0.24.0
    - r-performance >=0.12.4
    - r-pmcmrplus >=1.9.12
    - r-purrr >=1.0.2
    - r-rlang >=1.1.4
    - r-rstantools >=2.4.0
    - r-tidyr >=1.3.1
    - r-withr >=3.0.2
    - r-wrs2 >=1.1_6
    - r-zeallot >=0.1.0

test:
  commands:
    - $R -e "library('statsExpressions')"           # [not win]
    - "\"%R%\" -e \"library('statsExpressions')\""  # [win]

about:
  home: https://indrajeetpatil.github.io/statsExpressions/
  dev_url: https://github.com/IndrajeetPatil/statsExpressions
  license: GPL-3.0-only
  summary: "Statistical processing backend for 'ggstatsplot', this package creates expressions with details from statistical tests. It can additionally return dataframes with these results, which also make these functions a more pipe-friendly way to do statistical analysis. Currently, it supports only the most common types
    of statistical tests: parametric, nonparametric, robust, and Bayesian versions of t-test/ANOVA, correlation analyses, contingency table analysis, and meta-analysis."
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
