{% set version = "0.7.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-statsexpressions
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/statsExpressions_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/statsExpressions/statsExpressions_{{ version }}.tar.gz
  sha256: 4a7e65e6460c795b2050db31a73ad5b39a8cd979242bdb9684ca48ca64e402f3

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-bayesfactor
    - r-wrs2
    - r-afex
    - r-correlation
    - r-dplyr
    - r-effectsize >=0.4.3
    - r-insight >=0.12.0
    - r-ipmisc
    - r-metabma
    - r-metafor
    - r-metaplus
    - r-parameters >=0.11.0
    - r-performance
    - r-rlang
    - r-tidyr
  run:
    - r-base
    - r-bayesfactor
    - r-wrs2
    - r-afex
    - r-correlation
    - r-dplyr
    - r-effectsize >=0.4.3
    - r-insight >=0.12.0
    - r-ipmisc
    - r-metabma
    - r-metafor
    - r-metaplus
    - r-parameters >=0.11.0
    - r-performance
    - r-rlang
    - r-tidyr

test:
  commands:
    - $R -e "library('statsExpressions')"           # [not win]
    - "\"%R%\" -e \"library('statsExpressions')\""  # [win]

about:
  home: https://indrajeetpatil.github.io/statsExpressions/, https://github.com/IndrajeetPatil/statsExpressions
  license: GPL-3.0-only
  summary: "Statistical processing backend for 'ggstatsplot', this package creates expressions with details from statistical tests. It can additionally return dataframes with these results, which also make these functions a more pipe-friendly way to do statistical analysis. Currently, it supports only the most common types\
    \ of statistical tests: parametric, nonparametric, robust, and Bayesian versions of t-test/ANOVA, correlation analyses, contingency table analysis, and meta-analysis."
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Type: Package
# Package: statsExpressions
# Title: Expressions and Dataframes with Statistical Details
# Version: 0.6.1
# Authors@R: person(given = "Indrajeet", family = "Patil", role = c("cre", "aut", "cph"), email = "patilindrajeet.science@gmail.com", comment = c(ORCID = "0000-0003-1995-6531", Twitter = "@patilindrajeets"))
# Maintainer: Indrajeet Patil <patilindrajeet.science@gmail.com>
# Description: Statistical processing backend for 'ggstatsplot', this package creates expressions with details from statistical tests. It can additionally return dataframes with these results, which also make these functions a more pipe-friendly way to do statistical analysis. Currently, it supports only the most common types of statistical tests: parametric, nonparametric, robust, and Bayesian versions of t-test/ANOVA, correlation analyses, contingency table analysis, and meta-analysis.
# License: GPL-3 | file LICENSE
# URL: https://indrajeetpatil.github.io/statsExpressions/, https://github.com/IndrajeetPatil/statsExpressions
# BugReports: https://github.com/IndrajeetPatil/statsExpressions/issues
# Depends: R (>= 3.6.0)
# Imports: correlation, dplyr, effectsize, ez, insight (>= 0.11.0), ipmisc, metafor, metaplus, parameters (>= 0.10.0), performance (>= 0.6.0), rcompanion, rlang, stats, tidyBF, tidyr, WRS2
# Suggests: ggplot2, knitr, rmarkdown, spelling, testthat, utils
# VignetteBuilder: knitr
# Encoding: UTF-8
# Language: en-US
# LazyData: true
# RoxygenNote: 7.1.1
# Config/testthat/edition: 3
# Config/testthat/parallel: true
# Config/testthat/start-first: watcher, parallel*
# NeedsCompilation: no
# Packaged: 2020-12-01 20:53:46 UTC; inp099
# Author: Indrajeet Patil [cre, aut, cph] (<https://orcid.org/0000-0003-1995-6531>, @patilindrajeets)
# Repository: CRAN
# Date/Publication: 2020-12-01 21:50:03 UTC
