{% set version = "1.5.2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-statsexpressions
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/statsExpressions_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/statsExpressions/statsExpressions_{{ version }}.tar.gz
  sha256: d398ca8df27bd20c47c2b3f3f0ba0839e4044002cf230969a67f831b19371dd3

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-afex >=1.3_0
    - r-bayesfactor >=0.9.12_4.4
    - r-correlation >=0.8.4
    - r-datawizard >=0.7.1
    - r-dplyr >=1.1.2
    - r-effectsize >=0.8.3
    - r-glue
    - r-insight >=0.19.2
    - r-magrittr
    - r-parameters >=0.21.0
    - r-performance >=0.10.3
    - r-pmcmrplus >=1.9.6
    - r-purrr >=1.0.1
    - r-rlang
    - r-tibble >=3.2.1
    - r-tidyr >=1.3.0
    - r-withr
    - r-wrs2
    - r-zeallot
  run:
    - r-base
    - r-afex >=1.3_0
    - r-bayesfactor >=0.9.12_4.4
    - r-correlation >=0.8.4
    - r-datawizard >=0.7.1
    - r-dplyr >=1.1.2
    - r-effectsize >=0.8.3
    - r-glue
    - r-insight >=0.19.2
    - r-magrittr
    - r-parameters >=0.21.0
    - r-performance >=0.10.3
    - r-pmcmrplus >=1.9.6
    - r-purrr >=1.0.1
    - r-rlang
    - r-tibble >=3.2.1
    - r-tidyr >=1.3.0
    - r-withr
    - r-wrs2
    - r-zeallot

test:
  commands:
    - $R -e "library('statsExpressions')"           # [not win]
    - "\"%R%\" -e \"library('statsExpressions')\""  # [win]

about:
  home: https://indrajeetpatil.github.io/statsExpressions/
  dev_url: https://github.com/IndrajeetPatil/statsExpressions
  license: GPL-3.0-only
  summary: "Statistical processing backend for 'ggstatsplot', this package creates expressions with details from statistical tests. It can additionally return dataframes with these results, which also make these functions a more pipe-friendly way to do statistical analysis. Currently, it supports only the most common types
    of statistical tests: parametric, nonparametric, robust, and Bayesian versions of t-test/ANOVA, correlation analyses, contingency table analysis, and meta-analysis."
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Type: Package
# Package: statsExpressions
# Title: Expressions and Dataframes with Statistical Details
# Version: 0.6.1
# Authors@R: person(given = "Indrajeet", family = "Patil", role = c("cre", "aut", "cph"), email = "patilindrajeet.science@gmail.com", comment = c(ORCID = "0000-0003-1995-6531", Twitter = "@patilindrajeets"))
# Maintainer: Indrajeet Patil <patilindrajeet.science@gmail.com>
# Description: Statistical processing backend for 'ggstatsplot', this package creates expressions with details from statistical tests. It can additionally return dataframes with these results, which also make these functions a more pipe-friendly way to do statistical analysis. Currently, it supports only the most common types of statistical tests: parametric, nonparametric, robust, and Bayesian versions of t-test/ANOVA, correlation analyses, contingency table analysis, and meta-analysis.
# License: GPL-3 | file LICENSE
# URL: https://indrajeetpatil.github.io/statsExpressions/, https://github.com/IndrajeetPatil/statsExpressions
# BugReports: https://github.com/IndrajeetPatil/statsExpressions/issues
# Depends: R (>= 3.6.0)
# Imports: correlation, dplyr, effectsize, ez, insight (>= 0.11.0), ipmisc, metafor, metaplus, parameters (>= 0.10.0), performance (>= 0.6.0), rcompanion, rlang, stats, tidyBF, tidyr, WRS2
# Suggests: ggplot2, knitr, rmarkdown, spelling, testthat, utils
# VignetteBuilder: knitr
# Encoding: UTF-8
# Language: en-US
# LazyData: true
# RoxygenNote: 7.1.1
# Config/testthat/edition: 3
# Config/testthat/parallel: true
# Config/testthat/start-first: watcher, parallel*
# NeedsCompilation: no
# Packaged: 2020-12-01 20:53:46 UTC; inp099
# Author: Indrajeet Patil [cre, aut, cph] (<https://orcid.org/0000-0003-1995-6531>, @patilindrajeets)
# Repository: CRAN
# Date/Publication: 2020-12-01 21:50:03 UTC
