travis:
  secure:
    BINSTAR_TOKEN: nY4eQgQGiJIsYAbvm926NAG1DsXqChciYi1DKEISevyeGVO2BEOCn5wj2shkitkJ1unmUPHTzE1EAgdQKghGHR/mYqWF95+9Oqa7/mSv1OO+OMe1v2i/Ux3CCvmJhEUSvSpi12NWCqBHBoZoa4wBnX8pKkLB4OoMOm4ogPcJ3FFBbQ2khQeziPD5B/l3QGv/8yDALLDolRQzNFJxU36AuJfAZ6ZBPZ1unjc21OQJJ/095htOhtT2VG0JaPCTTxUpYlKlOtoCLHbBxG01ovWYLjylp6f9hBPhN5JGDISKFTPJNX/Jyln2cE+YwUj2R3gMTIPdWSeKugjKAnT+fFVndsfO8Uny1peMpy42nyaRfkRS++FV3nxAnh9TErrE6UcNHlmBm08pHqWcPJDcSKj4lXy3w+6Z/2IlQjJ1DAUU1w1gRH6NizNTywxSE2qEA7kJi/webPLEKDTeZH7L8mz1KKSNkeQrF9th2yOrq4mHDah8Q7HRy8UWK5aQBHPzDLOIjZ7YB5w3jgYZGlFNlU7ZxallR/IZa5Kt1DIFHbKfgfPGNijFknkYrXl5IM8FJnlzbBWnMO+D7w4LYCAWjJTs7n/H4K+m9Qdt7PQFSAqYLcZg8b87+8PP+zB6x0RQeS1YmVQeGa/G9hpqOXa/rt0Ay1CY7bQNkiTcFgK3D0RnQGQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
